version: '3'

services:
  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo:/data/db

  paysage-auth:
    image: ghcr.io/dataesr/paysage-auth:staging
    command: npm start
    depends_on:
       - mongo
    restart: always
    env_file:
      - .env
    ports:
      - 3004:3000

  paysage-api:
    build: .
    command: npm start
    env_file:
      - .env
      - .env.local
    ports:
      - 3003:3000
    depends_on:
      - mongo

volumes:
  mongo: