services:
  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
    restart: always
    command: --replSet rs0 --logpath /dev/null 
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo:/data/db
    networks:
      - paysage

  paysage-api:
    build: .
    command: npm start
    environment:
      - MONGO_URI=mongodb://mongo:27017
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mongo
    # volumes:
    #   - ./:/app
    networks:
      - paysage

volumes:
  mongo:

networks:
  paysage: {}