services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    expose:
      - 27017
    restart: always
    command: --replSet rs0 --logpath /dev/null --quiet 
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  paysage-api:
    build: .
    command: npm test
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongo:27017
