version: '3'

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    restart: always
    command: --replSet rs0 --logpath /dev/null --quiet 
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo:/data/db
  
  elasticsearch:
    image: dataesr/es_icu:1.1
    ports:
      - 9200:9200
    environment:
      - 'discovery.type=single-node'
    volumes:
      - elastic:/usr/share/elasticsearch/data

  paysage-auth:
    image: ghcr.io/dataesr/paysage-auth:staging
    command: npm start
    depends_on:
       - mongodb
    restart: always
    env_file:
      - .env
    ports:
      - 3004:3000

  paysage-api:
    build: .
    command: npm start
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    env_file:
      - .env
    ports:
      - 3003:3000
    depends_on:
      - mongodb

volumes:
  mongo:
  elastic: