version: '3'

services:
  elasticsearch:
    image: dataesr/es_icu:7.12.0
    ports:
      - 9200:9200
    environment:
      - 'discovery.type=single-node'
    healthcheck:
      test: curl -s -f elasticsearch:9200/_cat/health > /dev/null || exit 1
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - elastic:/usr/share/elasticsearch/data

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    restart: always
    command: --replSet rs0 --logpath /dev/null --quiet 
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo:/data/db

  paysage-auth:
    image: ghcr.io/dataesr/paysage-auth:staging
    command: npm start
    depends_on:
       - mongodb
    restart: always
    env_file:
      - .env
    ports:
      - 3004:3000

  paysage-api:
    build: .
    command: npm start
    environment:
      - ES_NODE=http://elasticsearch:9200
      - ES_PASSWORD=
      - ES_USERNAME=
      - MONGO_URI=mongodb://mongodb:27017
    env_file:
      - .env
    ports:
      - 3003:3000
    depends_on:
      elasticsearch:
        condition: service_healthy
      mongodb:
        condition: service_started

volumes:
  mongo:
  elastic: