import 'dotenv/config';

import logger from '../services/logger.service';
import { client, db } from '../services/mongo.service';

async function setupMongo() {
  await db.collection('categories').createIndex({ id: 1 }, { unique: true });
  await db.collection('categories').createIndex({ createdAt: 1 });
  await db.collection('contact').createIndex({ id: 1 }, { unique: true });
  await db.collection('contact').createIndex({ createdAt: 1 });
  await db.collection('documents').createIndex({ id: 1 }, { unique: true });
  await db.collection('documents').createIndex({ createdAt: 1 });
  await db.collection('documents').createIndex({ relatesTo: 1 });
  await db.collection('documenttypes').createIndex({ id: 1 }, { unique: true });
  await db.collection('documenttypes').createIndex({ createdAt: 1 });
  await db.collection('emails').createIndex({ id: 1 }, { unique: true });
  await db.collection('emails').createIndex({ createdAt: 1 });
  await db.collection('emails').createIndex({ resourceId: 1 });
  await db.collection('emailtypes').createIndex({ id: 1 }, { unique: true });
  await db.collection('emailtypes').createIndex({ createdAt: 1 });
  await db.collection('followups').createIndex({ id: 1 }, { unique: true });
  await db.collection('followups').createIndex({ createdAt: 1 });
  await db.collection('followups').createIndex({ relatesTo: 1 });
  await db.collection('geographicalcategories').createIndex({ id: 1 }, { unique: true });
  await db.collection('geographicalcategories').createIndex({ originalId: 1 }, { unique: true });
  await db.collection('geographicalexceptions').createIndex({ geographicalCategoryId: 1 });
  await db.collection('geographicalexceptions').createIndex({ resourceId: 1 });
  await db.collection('geographicalexceptions').createIndex({ geographicalCategoryId: 1, resourceId: 1 }, { unique: true });
  await db.collection('groups').createIndex({ id: 1 }, { unique: true });
  await db.collection('groups').createIndex({ createdAt: 1 });
  await db.collection('groupmembers').createIndex({ userId: 1, groupId: 1 }, { unique: true });
  await db.collection('groupmembers').createIndex({ userId: 1 });
  await db.collection('groupmembers').createIndex({ createdAt: 1 });
  await db.collection('groups').createIndex({ id: 1 }, { unique: true });
  await db.collection('groups').createIndex({ createdAt: 1 });
  await db.collection('identifiers').createIndex({ id: 1 }, { unique: true });
  await db.collection('identifiers').createIndex({ createdAt: 1 });
  await db.collection('identifiers').createIndex({ resourceId: 1 });
  await db.collection('identifiers').createIndex({ resourceId: 1, type: 1 });
  await db.collection('keynumbers').createIndex({ dataset: 1, resourceId: 1 });
  await db.collection('keynumbers').createIndex({ dataset: 1, resourceId: 1, annee: 1 }, { sparse: true });
  await db.collection('keynumbers').createIndex({ dataset: 1, resourceId: 1, rentree: 1 }, { sparse: true });
  await db.collection('keynumbers').createIndex({ annee_universitaire: 1 }, { sparse: true });
  await db.collection('keynumbers').createIndex({ exercice: 1 }, { sparse: true });
  await db.collection('legalcategories').createIndex({ id: 1 }, { unique: true });
  await db.collection('legalcategories').createIndex({ createdAt: 1 });
  await db.collection('officialtexts').createIndex({ id: 1 }, { unique: true });
  await db.collection('officialtexts').createIndex({ createdAt: 1 });
  await db.collection('officialtexts').createIndex({ relatesTo: 1 });
  await db.collection('persons').createIndex({ id: 1 }, { unique: true });
  await db.collection('persons').createIndex({ createdAt: 1 });
  await db.collection('press').createIndex({ id: 1 }, { unique: true });
  await db.collection('press').createIndex({ createdAt: 1 });
  await db.collection('press').createIndex({ alertId: 1 }, { unique: true });
  await db.collection('press').createIndex({ relatesTo: 1 });
  await db.collection('press').createIndex({ matchedWith: 1 });
  await db.collection('press').createIndex({ excluded: 1 });
  await db.collection('prizes').createIndex({ id: 1 }, { unique: true });
  await db.collection('prizes').createIndex({ createdAt: 1 });
  await db.collection('projects').createIndex({ id: 1 }, { unique: true });
  await db.collection('projects').createIndex({ createdAt: 1 });
  await db.collection('relationships').createIndex({ id: 1 }, { unique: true });
  await db.collection('relationships').createIndex({ createdAt: 1 });
  await db.collection('relationships').createIndex({ resourceId: 1 });
  await db.collection('relationships').createIndex({ resourceId: 1, relationTag: 1 });
  await db.collection('relationships').createIndex({ relatedObjectId: 1 });
  await db.collection('relationships').createIndex({ relatedObjectId: 1, relationTag: 1 });
  await db.collection('relationships').createIndex({ otherAssociatedObjectIds: 1, relationTag: 1 });
  await db.collection('relationships').createIndex({ relationsGroupId: 1 });
  await db.collection('relationtypes').createIndex({ id: 1 }, { unique: true });
  await db.collection('relationtypes').createIndex({ for: 1 });
  await db.collection('socialmedias').createIndex({ id: 1 }, { unique: true });
  await db.collection('socialmedias').createIndex({ createdAt: 1 });
  await db.collection('socialmedias').createIndex({ resourceId: 1 });
  await db.collection('structures').createIndex({ id: 1 }, { unique: true });
  await db.collection('structures').createIndex({ createdAt: 1 });
  await db.collection('supervisingministers').createIndex({ id: 1 }, { unique: true });
  await db.collection('supervisingministers').createIndex({ createdAt: 1 });
  await db.collection('terms').createIndex({ id: 1 }, { unique: true });
  await db.collection('terms').createIndex({ createdAt: 1 });
  await db.collection('tokens').createIndex({ expireAt: 1 }, { expireAfterSeconds: 0 });
  await db.collection('tokens').createIndex({ token: 1, userAgent: 1 });
  await db.collection('users').createIndex({ email: 1 }, { unique: true });
  await db.collection('users').createIndex({ createdAt: 1 });
  await db.collection('users').createIndex({ id: 1 }, { unique: true });
  await db.collection('weblinks').createIndex({ id: 1 }, { unique: true });
  await db.collection('weblinks').createIndex({ createdAt: 1 });
  await db.collection('weblinks').createIndex({ resourceId: 1 });
  logger.info('Mongodb setup successful');
  if (client) {
    await client.close();
  }
  logger.info('Mongodb connexion closed');
  process.exit(0);
}

setupMongo().catch((e) => {
  logger.error({ ...e, message: 'Mongodb setup failed' });
  process.exit(1);
});
