title: Person
description: Object décrivant une personne
allOf:
  - type: object
    properties:
      nameFr:
        type: string
        nullable: true
      nameEn:
        type: string
        nullable: true
      fullNameFr:
        type: string
        nullable: true
      fullNameEn:
        type: string
        nullable: true
      acronymFr:
        type: string
        nullable: true
      acronymEn:
        type: string
        nullable: true
      descriptionEn:
        type: string
        nullable: true
      descriptionFr:
        type: string
        nullable: true
      startDate:
        type: string
        nullable: true
        pattern: '((^$)|(^\d{4}$)|(^\d{4}-(0[1-9]|1[0-2]))|(^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$))'
      endDate:
        type: string
        nullable: true
        pattern: '((^$)|(^\d{4}$)|(^\d{4}-(0[1-9]|1[0-2]))|(^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$))'
      grantPart:
        type: string
        nullable: true
      funding:
        type: number
        nullable: true
      comment:
        type: string
        nullable: true
  - $ref: '../../api.yml#/components/schemas/Metas'