openapi: 3.0.1
info:
  title: Paysage-api.
  description: Documentation for the Paysage rest API routes.
  contact:
    email: frederic.olland@enseignementsup.gouv.fr
  license:
    name: MIT
    url: 'https://github.com/dataesr/paysage-api/LICENCE.md'
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/'


paths:

  ### STRUCTURE ###
  '/api/structures':
    $ref: 'modules/structure/swagger/path/structures.yml'
  '/api/structures/{id}':
    $ref: 'modules/structure/swagger/path/structure.yml'
  '/api/structures/{id}/identifiers':
    $ref: 'modules/structure/swagger/path/identifiers.yml'
