openapi: 3.0.1
info:
  title: Paysage-api.
  description: Documentation for the Paysage rest API routes.
  contact:
    email: frederic.olland@enseignementsup.gouv.fr
  license:
    name: MIT
    url: 'https://github.com/dataesr/paysage-api/LICENCE.md'
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/'


paths:

  ### STRUCTURE ###
  '/api/structure/all':
    $ref: 'modules/structure/swagger/path/all.yml'
  '/api/structure/{id}':
    $ref: 'modules/structure/swagger/path/one.yml'
  '/api/structure/add':
    $ref: 'modules/structure/swagger/path/add.yml'
  '/api/structure/{id}/description':
    $ref: 'modules/structure/swagger/path/description.yml'
