openapi: 3.0.1
info:
  title: Authentication.
  description: Authentication and UserManagment api.
  contact:
    email: frederic.olland@enseignementsup.gouv.fr
  license:
    name: MIT
    url: 'https://github.com/dataesr/paysage-api/LICENCE.md'
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/'
  - url: 'https://api.paysage.staging.dataesr.ovh/'
  - url: 'https://api.paysage.dataesr.ovh/'
paths:
  /test:
    post:
      responses:
        '200':
          description: OK
