name: Docs deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy-docs :
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Deploy to Cluster
        run: |
          git checkout docs
          npm i
          npm run build:docs
          shopt -s extglob
          sudo rm -rf !(docs)
          ls
          git config --global user.name 'folland87'
          git config --global user.email 'folland87@users.noreply.github.com'
          git add .
          git commit -m 'deploy docs'
          git push origin --force HEAD:docs

