name: Docs deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy-docs :
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Deploy to Cluster
        run: |
          npm i swagger-cli
          npm run build:docs
          cd docs
          ls
          npx @stoplight/cli@5 push --ci-token ${{ secrets.STOPLIGHT_TOKEN }} --url https://dataesr.stoplight.io/


