name: Staging deployment

on:
  push:
    branches:
      - staging

env:
  # Must match k8s deployment name
  DEPLOYMENT: paysage-api
  DEPLOYMENT_NAMESPACE: paysage
  DEPLOYMENT_URL: https://docs.paysage.dataesr.ovh/docs/paysage-api-1
  MM_NOTIFICATION_CHANNEL: 'bots'

jobs:
  publish-ghcr:
    name: Publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log into registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build -f Dockerfile -t ${{ github.repository }} .

      - name: Get Tag
        id: version
        run: echo "tag=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker tag ${{ github.repository }} $IMAGE_ID:${{ steps.version.outputs.tag }}
          docker push $IMAGE_ID:${{ steps.version.outputs.tag }}

  deploy-docs :
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docs
        run: |
          npm i swagger-cli
          npm run docs:build
      - name: Push to stoplight
        run: |
          cd docs
          npx @stoplight/cli@5 push --ci-token ${{ secrets.STOPLIGHT_TOKEN }} --url https://dataesr.stoplight.io/

  deploy:
    name: Update staging deployment
    runs-on: ubuntu-latest
    needs: publish-ghcr
    steps:
      - name: Deploy to Cluster
        id: kubectl-deploy
        uses: dataesr/kubectl-deploy@v1.1
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DOAD_STAGING }}
        with:
          namespace: ${{ env.DEPLOYMENT_NAMESPACE }}
          restart: ${{ env.DEPLOYMENT }}

  notify:
    needs: deploy
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: dataesr/mm-notifier-action@v1.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          mattermost_webhook_url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          mattermost_channel: ${{ env.MM_NOTIFICATION_CHANNEL}}
          deployment_url: ${{ env.DEPLOYMENT_URL }}