name: Tests

on: push
env:
  DEPLOYMENT_URL: https://docs.paysage.dataesr.ovh/docs/paysage-api-1
  MM_NOTIFICATION_CHANNEL: 'bots'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: docker compose -f docker-compose-test.yml up --build --exit-code-from paysage-api

  notify:
    needs: tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: dataesr/mm-notifier-action@v1.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          mattermost_webhook_url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          mattermost_channel: ${{ env.MM_NOTIFICATION_CHANNEL}}
          deployment_url: ${{ env.DEPLOYMENT_URL }}