name: Tests

on: push
env:
  DEPLOYMENT_URL: https://docs.paysage.dataesr.ovh/docs/paysage-api-1
  SLACK_NOTIFICATION_CHANNEL: '#paysage-bot'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml up --build --exit-code-from paysage-api

  notify:
    needs: tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dataesr/slack-notifier-action@v1
        with:
          deployment_url: ${{ env.DEPLOYMENT_URL }}
          github_token: ${{ secrets.GITHUB_TOKEN}}
          slack_channel: ${{ env.SLACK_NOTIFICATION_CHANNEL}}
          slack_token: ${{ secrets.SLACK_TOKEN }}