name: Tests

on:
  push:
    branches:
      - dev

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: docker-compose up --build --exit-code-from app

  notify:
    needs: deploy
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dataesr/slack-notifier-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          slack_channel: ${{ env.SLACK_NOTIFICATION_CHANNEL}}
          deployment_url: ${{ env.DEPLOYMENT_URL }}