openapi: 3.0.1
info:
  title: API
  description: Documentation for the Paysage rest API routes.
  contact:
    email: frederic.olland@enseignementsup.gouv.fr
  license:
    name: MIT
    url: 'https://github.com/dataesr/paysage-api/LICENCE.md'
  version: 1.0.0
servers:
  - url: 'https://api.paysage.staging.dataesr.ovh/'
    description: Staging server
  - url: 'https://api.paysage.dataesr.ovh/'
    description: Production server
  - url: 'http://localhost:3000/'
    description: Development server

tags:
  - name: Structures
  - name: Structures - Noms
  - name: Structures - Identifiants
  - name: Structures - Localisations
  - name: Structures - Liens web
  - name: Structures - Médias sociaux
  - name: Structures - Logos
  # - name: Structures - Agenda
  # - name: Structures - Documents
  - name: Structures - Catégories
  # - name: Structures - Gouvernance
  # - name: Structures - Référents MESRI
  # - name: Structures - Tutelles
  # - name: Structures - Parents
  # - name: Structures - Enfants
  - name: Personnes
  - name: Personnes - Identifiants
  - name: Personnes - Médias sociaux
  - name: Personnes - Liens web
  # - name: Personnes - Rôles
  # - name: Personnes - Prix
  - name: Catégories
  - name: Catégories - Identifiants
  - name: Catégories - Liens web
  - name: Termes
  - name: Documents officiels
  - name: Documents
  - name: Catégories juridiques
  - name: Prix scientifiques
  # - name: Projects
  # - name: Events

security:
  - BearerAuth: []

paths:
  ### STRUCTURE ###
  '/structures':
    $ref: './paths/structures/structures.yml#/~1structures'
  '/structures/{structureId}':
    $ref: './paths/structures/structures.yml#/~1structures~1{structureId}'
  '/structures/{structureId}/identifiers':
    $ref: './paths/structures/identifiers.yml#/~1structures~1{structureId}~1identifiers'
  '/structures/{structureId}/identifiers/{identifierId}':
    $ref: './paths/structures/identifiers.yml#/~1structures~1{structureId}~1identifiers~1{identifierId}'
  '/structures/{structureId}/localisations':
    $ref: './paths/structures/localisations.yml#/~1structures~1{structureId}~1localisations'
  '/structures/{structureId}/localisations/{localisationId}':
    $ref: './paths/structures/localisations.yml#/~1structures~1{structureId}~1localisations~1{localisationId}'
  '/structures/{structureId}/logos':
    $ref: './paths/structures/logos.yml#/~1structures~1{structureId}~1logos'
  '/structures/{structureId}/logos/{logoId}':
    $ref: './paths/structures/logos.yml#/~1structures~1{structureId}~1logos~1{logoId}'
  '/structures/{structureId}/names':
    $ref: './paths/structures/names.yml#/~1structures~1{structureId}~1names'
  '/structures/{structureId}/names/{nameId}':
    $ref: './paths/structures/names.yml#/~1structures~1{structureId}~1names~1{nameId}'
  '/structures/{structureId}/weblinks':
    $ref: './paths/structures/weblinks.yml#/~1structures~1{structureId}~1weblinks'
  '/structures/{structureId}/weblinks/{weblinkId}':
    $ref: './paths/structures/weblinks.yml#/~1structures~1{structureId}~1weblinks~1{weblinkId}'
  '/structures/{structureId}/socialmedias':
    $ref: './paths/structures/socialmedias.yml#/~1structures~1{structureId}~1socialmedias'
  '/structures/{structureId}/socialmedias/{socialmediaId}':
    $ref: './paths/structures/socialmedias.yml#/~1structures~1{structureId}~1socialmedias~1{socialmediaId}'
  '/structures/{structureId}/categories':
    $ref: './paths/structures/categories.yml#/~1structures~1{structureId}~1categories'
  '/structures/{structureId}/categories/{relatedCategoryId}':
    $ref: './paths/structures/categories.yml#/~1structures~1{structureId}~1categories~1{relatedCategoryId}'
  
  ### PERSONNES ###
  '/persons':
    $ref: './paths/persons/persons.yml#/~1persons'
  '/persons/{personId}':
    $ref: './paths/persons/persons.yml#/~1persons~1{personId}'
  '/persons/{personId}/identifiers':
    $ref: './paths/persons/identifiers.yml#/~1persons~1{personId}~1identifiers'
  '/persons/{personId}/identifiers/{identifierId}':
    $ref: './paths/persons/identifiers.yml#/~1persons~1{personId}~1identifiers~1{identifierId}'
  '/persons/{personId}/weblinks':
    $ref: './paths/persons/weblinks.yml#/~1persons~1{personId}~1weblinks'
  '/persons/{personId}/weblinks/{weblinkId}':
    $ref: './paths/persons/weblinks.yml#/~1persons~1{personId}~1weblinks~1{weblinkId}'
  '/persons/{personId}/socialmedias':
    $ref: './paths/persons/socialmedias.yml#/~1persons~1{personId}~1socialmedias'
  '/persons/{personId}/socialmedias/{socialmediaId}':
    $ref: './paths/persons/socialmedias.yml#/~1persons~1{personId}~1socialmedias~1{socialmediaId}'

  ### TERMES ###
  '/terms':
    $ref: './paths/terms/terms.yml#/~1terms'
  '/terms/{termId}':
    $ref: './paths/terms/terms.yml#/~1terms~1{termId}'

  ### CATEGORIES JURIDIQUES ###
  '/legalcategories':
    $ref: './paths/legalcategories/legalcategories.yml#/~1legalcategories'
  '/legalcategories/{legalCategoryId}':
    $ref: './paths/legalcategories/legalcategories.yml#/~1legalcategories~1{legalCategoryId}'

  ### CATEGORIES ###
  '/categories':
    $ref: './paths/categories/categories.yml#/~1categories'
  '/categories/{categoryId}':
    $ref: './paths/categories/categories.yml#/~1categories~1{categoryId}'
  '/categories/{categoryId}/identifiers':
    $ref: './paths/categories/identifiers.yml#/~1categories~1{categoryId}~1identifiers'
  '/categories/{categoryId}/identifiers/{identifierId}':
    $ref: './paths/categories/identifiers.yml#/~1categories~1{categoryId}~1identifiers~1{identifierId}'
  '/categories/{categoryId}/weblinks':
    $ref: './paths/categories/weblinks.yml#/~1categories~1{categoryId}~1weblinks'
  '/categories/{categoryId}/weblinks/{weblinkId}':
    $ref: './paths/categories/weblinks.yml#/~1categories~1{categoryId}~1weblinks~1{weblinkId}'

  ### OFFICIAL DOCUMENTS ###
  '/officialdocuments':
    $ref: './paths/officialdocuments/officialdocuments.yml#/~1officialdocuments'
  '/officialdocuments/{officialDocumentId}':
    $ref: './paths/officialdocuments/officialdocuments.yml#/~1officialdocuments~1{officialDocumentId}'

  ### DOCUMENTS ###
  '/documents':
    $ref: './paths/documents/documents.yml#/~1documents'
  '/documents/{documentId}':
    $ref: './paths/documents/documents.yml#/~1documents~1{documentId}'

  ### PRIX SCIENTIFIQUES ###
  '/prices':
    $ref: './paths/prices/prices.yml#/~1prices'
  '/prices/{priceId}':
    $ref: './paths/prices/prices.yml#/~1prices~1{priceId}'

components:
  parameters:
    filters:
      $ref: ./parameters/query/filters.yml
    skip:
      $ref: ./parameters/query/skip.yml
    limit:
      $ref: ./parameters/query/limit.yml
    sort:
      $ref: ./parameters/query/sort.yml
    documentId:
      $ref: ./parameters/ids/document-id.yml
    structureId:
      $ref: ./parameters/ids/structure-id.yml
    nameId:
      $ref: ./parameters/ids/name-id.yml
    logoId:
      $ref: ./parameters/ids/logo-id.yml
    identifierId:
      $ref: ./parameters/ids/identifier-id.yml
    localisationId:
      $ref: ./parameters/ids/localisation-id.yml
    weblinkId:
      $ref: ./parameters/ids/weblink-id.yml
    socialmediaId:
      $ref: ./parameters/ids/socialmedia-id.yml
    termId:
      $ref: ./parameters/ids/term-id.yml
    categoryId:
      $ref: ./parameters/ids/category-id.yml
    relatedCategoryId:
      $ref: ./parameters/ids/related-category-id.yml
    legalCategoryId:
      $ref: ./parameters/ids/legal-category-id.yml
    priceId:
      $ref: ./parameters/ids/price-id.yml
    personId:
      $ref: ./parameters/ids/person-id.yml
    officialDocumentId:
      $ref: ./parameters/ids/officialdocument-id.yml
    newsId:
      $ref: ./parameters/ids/news-id.yml
    roleId:
      $ref: ./parameters/ids/role-id.yml

  responses:
    BadRequest:
      $ref: './responses/errors/bad-request.yml'
    NotFound:
      $ref: './responses/errors/not-found.yml'
    Forbidden:
      $ref: './responses/errors/forbidden.yml'
    Unauthorized:
      $ref: './responses/errors/unauthorized.yml'
    ServerError:
      $ref: './responses/errors/server-error.yml'

  schemas:
    ### MODELS ###
    Structure:
      $ref: './schemas/structures/structure.yml'
    StructureLight:
      $ref: './schemas/structures/structure-light.yml'
    StructureName:
      $ref: './schemas/structures/name.yml'
    StructureNameLight:
      $ref: './schemas/structures/name-light.yml'
    StructureCategory:
      $ref: './schemas/structures/category.yml'
    StructureIdentifier:
      $ref: './schemas/structures/identifier.yml'
    StructureLocalisation:
      $ref: './schemas/structures/localisation.yml'
    StructureLocalisationLight:
      $ref: './schemas/structures/localisation-light.yml'
    Weblink:
      $ref: './schemas/commons/weblink.yml'
    Logo:
      $ref: './schemas/commons/logo.yml'
    SocialMedia:
      $ref: './schemas/commons/socialmedia.yml'
    OfficialDocument:
      $ref: './schemas/officialdocuments/officialdocument.yml'
    OfficialDocumentLight:
      $ref: './schemas/officialdocuments/officialdocument-light.yml'
    Document:
      $ref: './schemas/documents/document.yml'
    DocumentLight:
      $ref: './schemas/documents/document-light.yml'
    Category:
      $ref: './schemas/categories/category.yml'
    CategoryLight:
      $ref: './schemas/categories/category-light.yml'
    CategoryIdentifier:
      $ref: './schemas/categories/identifier.yml'
    Price:
      $ref: './schemas/prices/price.yml'
    PriceLight:
      $ref: './schemas/prices/price-light.yml'
    Person:
      $ref: './schemas/persons/person.yml'
    PersonLight:
      $ref: './schemas/persons/person-light.yml'
    PersonIdentifier:
      $ref: './schemas/persons/identifier.yml'
    Role:
      $ref: './schemas/roles/role.yml'
    RoleLight:
      $ref: './schemas/roles/role-light.yml'
    Term:
      $ref: './schemas/terms/term.yml'
    TermLight:
      $ref: './schemas/terms/term-light.yml'
    LegalCategory:
      $ref: './schemas/legalcategories/legalcategory.yml'
    LegalCategoryLight:
      $ref: './schemas/legalcategories/legalcategory-light.yml'


    ### PAYLOADS ###
    StructureCreatePayload:
      $ref: './schemas/structures/structure-create-payload.yml'
    StructureUpdatePayload:
      $ref: './schemas/structures/structure-update-payload.yml'
    StructureCategoryPayload:
      $ref: './schemas/structures/category-payload.yml'
    StructureIdentifierPayload:
      $ref: './schemas/structures/identifier-payload.yml'
    StructureNamePayload:
      $ref: './schemas/structures/name-payload.yml'
    StructureLocalisationPayload:
      $ref: './schemas/structures/localisation-payload.yml'
    CategoryPayload:
      $ref: './schemas/categories/category-payload.yml'
    CategoryIdentifierPayload:
      $ref: './schemas/categories/identifier-payload.yml'

    PersonPayload:
      $ref: './schemas/persons/person-payload.yml'
    PersonIdentifierPayload:
      $ref: './schemas/persons/identifier-payload.yml'

    PricePayload:
      $ref: './schemas/prices/price-payload.yml'

    TermPayload:
      $ref: './schemas/terms/term-payload.yml'

    LegalCategoryPayload:
      $ref: './schemas/legalcategories/legalcategory-payload.yml'

    DocumentPayload:
      $ref: './schemas/documents/document-payload.yml'

    OfficialDocumentPayload:
      $ref: './schemas/officialdocuments/officialdocument-payload.yml'

    LogoPayload:
      $ref: './schemas/commons/logo-payload.yml'
    WeblinkPayload:
      $ref: './schemas/commons/weblink-payload.yml'
    SocialMediaPayload:
      $ref: './schemas/commons/socialmedia-payload.yml'

    RolePayload:
      $ref: './schemas/roles/role-payload.yml'


    ### ENUMS ###
    StructureIdentifierTypesEnum:
      $ref: './schemas/structures/enums/identifier-types.yml'
    PersonIdentifierTypesEnum:
      $ref: './schemas/persons/enums/identifier-types.yml'
    CategoryIdentifierTypesEnum:
      $ref: './schemas/categories/enums/identifier-types.yml'
    OfficialDocumentTypesEnum:
      $ref: './schemas/officialdocuments/enums/type.yml'
    OfficialDocumentNaturesEnum:
      $ref: './schemas/officialdocuments/enums/nature.yml'
    WeblinkTypesEnum:
      $ref: './schemas/commons/enums/weblink-types.yml'


    ### COMMON MODELS ###
    Error:
      $ref: './schemas/commons/error.yml'
    Metas:
      $ref: './schemas/commons/metas.yml'

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: Authentication with a Bearer token.