openapi: 3.0.1
info:
  title: API
  description: Documentation for the Paysage rest API routes.
  contact:
    email: frederic.olland@enseignementsup.gouv.fr
  license:
    name: MIT
    url: 'https://github.com/dataesr/paysage-api/LICENCE.md'
  version: 1.0.0
servers:
  - url: 'https://api.paysage.staging.dataesr.ovh/'
    description: Staging server
  - url: 'https://api.paysage.dataesr.ovh/'
    description: Production server
  - url: 'http://localhost:3000/'
    description: Development server

tags:
  - name: Catégories
  - name: Catégories juridiques
  - name: Catégories - Identifiants
  - name: Catégories - Liens web
  - name: Catégories - Médias sociaux
  - name: Documents
  - name: Documentation
  - name: Personnes
  - name: Personnes - Identifiants
  - name: Personnes - Médias sociaux
  - name: Personnes - Liens web
  - name: Personnes - Catégories
  - name: Prix scientifiques
  - name: Projets
  - name: Projets - Liens web
  - name: Projets - Localisations
  - name: Structures
  - name: Structures - Noms
  - name: Structures - Identifiants
  - name: Structures - Localisations
  - name: Structures - Liens web
  - name: Structures - Médias sociaux
  - name: Structures - Logos
  - name: Structures - Catégories
  - name: Structures - Status juridiques
  - name: Structures - Emails
  - name: Termes
  - name: Termes - Liens web
  - name: Termes - Médias sociaux
  - name: Textes officiels
  - name: Types de documents
  - name: Types d'email

security:
  - BearerAuth: []

paths:
  ### OPENAPI DOCUMENTATION ###
  '/docs/specs':
    $ref: './paths/docs/docs.yml#/~1docs~1specs'
  '/docs/enums':
    $ref: './paths/docs/docs.yml#/~1docs~1enums'
  ### STRUCTURE ###
  '/structures':
    $ref: './paths/structures/structures.yml#/~1structures'
  '/structures/{structureId}':
    $ref: './paths/structures/structures.yml#/~1structures~1{structureId}'
  '/structures/{structureId}/categories':
    $ref: './paths/structures/categories.yml#/~1structures~1{structureId}~1categories'
  '/structures/{structureId}/categories/{relatedCategoryId}':
    $ref: './paths/structures/categories.yml#/~1structures~1{structureId}~1categories~1{relatedCategoryId}'
  '/structures/{structureId}/emails':
    $ref: './paths/structures/emails.yml#/~1structures~1{structureId}~1emails'
  '/structures/{structureId}/emails/{emailId}':
    $ref: './paths/structures/emails.yml#/~1structures~1{structureId}~1emails~1{emailId}'
  '/structures/{structureId}/identifiers':
    $ref: './paths/structures/identifiers.yml#/~1structures~1{structureId}~1identifiers'
  '/structures/{structureId}/identifiers/{identifierId}':
    $ref: './paths/structures/identifiers.yml#/~1structures~1{structureId}~1identifiers~1{identifierId}'
  '/structures/{structureId}/legal-categories':
    $ref: './paths/structures/legal-categories.yml#/~1structures~1{structureId}~1legal-categories'
  '/structures/{structureId}/legal-categories/{relatedLegalCategoryId}':
    $ref: './paths/structures/legal-categories.yml#/~1structures~1{structureId}~1legal-categories~1{relatedLegalCategoryId}'
  '/structures/{structureId}/localisations':
    $ref: './paths/structures/localisations.yml#/~1structures~1{structureId}~1localisations'
  '/structures/{structureId}/localisations/{localisationId}':
    $ref: './paths/structures/localisations.yml#/~1structures~1{structureId}~1localisations~1{localisationId}'
  '/structures/{structureId}/logos':
    $ref: './paths/structures/logos.yml#/~1structures~1{structureId}~1logos'
  '/structures/{structureId}/logos/{logoId}':
    $ref: './paths/structures/logos.yml#/~1structures~1{structureId}~1logos~1{logoId}'
  '/structures/{structureId}/names':
    $ref: './paths/structures/names.yml#/~1structures~1{structureId}~1names'
  '/structures/{structureId}/names/{nameId}':
    $ref: './paths/structures/names.yml#/~1structures~1{structureId}~1names~1{nameId}'
  '/structures/{structureId}/social-medias':
    $ref: './paths/structures/social-medias.yml#/~1structures~1{structureId}~1social-medias'
  '/structures/{structureId}/social-medias/{socialmediaId}':
    $ref: './paths/structures/social-medias.yml#/~1structures~1{structureId}~1social-medias~1{socialmediaId}'
  '/structures/{structureId}/weblinks':
    $ref: './paths/structures/weblinks.yml#/~1structures~1{structureId}~1weblinks'
  '/structures/{structureId}/weblinks/{weblinkId}':
    $ref: './paths/structures/weblinks.yml#/~1structures~1{structureId}~1weblinks~1{weblinkId}'
  
  ### PERSONNES ###
  '/persons':
    $ref: './paths/persons/persons.yml#/~1persons'
  '/persons/{personId}':
    $ref: './paths/persons/persons.yml#/~1persons~1{personId}'
  '/persons/{personId}/identifiers':
    $ref: './paths/persons/identifiers.yml#/~1persons~1{personId}~1identifiers'
  '/persons/{personId}/identifiers/{identifierId}':
    $ref: './paths/persons/identifiers.yml#/~1persons~1{personId}~1identifiers~1{identifierId}'
  '/persons/{personId}/weblinks':
    $ref: './paths/persons/weblinks.yml#/~1persons~1{personId}~1weblinks'
  '/persons/{personId}/weblinks/{weblinkId}':
    $ref: './paths/persons/weblinks.yml#/~1persons~1{personId}~1weblinks~1{weblinkId}'
  '/persons/{personId}/social-medias':
    $ref: './paths/persons/social-medias.yml#/~1persons~1{personId}~1social-medias'
  '/persons/{personId}/social-medias/{socialmediaId}':
    $ref: './paths/persons/social-medias.yml#/~1persons~1{personId}~1social-medias~1{socialmediaId}'
  '/persons/{personId}/categories':
    $ref: './paths/persons/categories.yml#/~1persons~1{personId}~1categories'
  '/persons/{personId}/categories/{relationshipId}':
    $ref: './paths/persons/categories.yml#/~1persons~1{personId}~1categories~1{relationshipId}'

  ### TERMES ###
  '/terms':
    $ref: './paths/terms/terms.yml#/~1terms'
  '/terms/{termId}':
    $ref: './paths/terms/terms.yml#/~1terms~1{termId}'
  '/terms/{termId}/weblinks':
    $ref: './paths/terms/weblinks.yml#/~1terms~1{termId}~1weblinks'
  '/terms/{termId}/weblinks/{weblinkId}':
    $ref: './paths/terms/weblinks.yml#/~1terms~1{termId}~1weblinks~1{weblinkId}'
  '/terms/{termId}/social-medias':
    $ref: './paths/terms/social-medias.yml#/~1terms~1{termId}~1social-medias'
  '/terms/{termId}/social-medias/{socialmediaId}':
    $ref: './paths/terms/social-medias.yml#/~1terms~1{termId}~1social-medias~1{socialmediaId}'

  ### CATEGORIES JURIDIQUES ###
  '/legal-categories':
    $ref: './paths/legalcategories/legalcategories.yml#/~1legal-categories'
  '/legal-categories/{legalCategoryId}':
    $ref: './paths/legalcategories/legalcategories.yml#/~1legal-categories~1{legalCategoryId}'

  ### CATEGORIES ###
  '/categories':
    $ref: './paths/categories/categories.yml#/~1categories'
  '/categories/{categoryId}':
    $ref: './paths/categories/categories.yml#/~1categories~1{categoryId}'
  '/categories/{categoryId}/identifiers':
    $ref: './paths/categories/identifiers.yml#/~1categories~1{categoryId}~1identifiers'
  '/categories/{categoryId}/identifiers/{identifierId}':
    $ref: './paths/categories/identifiers.yml#/~1categories~1{categoryId}~1identifiers~1{identifierId}'
  '/categories/{categoryId}/weblinks':
    $ref: './paths/categories/weblinks.yml#/~1categories~1{categoryId}~1weblinks'
  '/categories/{categoryId}/weblinks/{weblinkId}':
    $ref: './paths/categories/weblinks.yml#/~1categories~1{categoryId}~1weblinks~1{weblinkId}'
  '/categories/{categoryId}/social-medias':
    $ref: './paths/categories/social-medias.yml#/~1categories~1{categoryId}~1social-medias'
  '/categories/{categoryId}/social-medias/{socialmediaId}':
    $ref: './paths/categories/social-medias.yml#/~1categories~1{categoryId}~1social-medias~1{socialmediaId}'
  
  ### OFFICIAL TEXTS ###
  '/official-texts':
    $ref: './paths/officialtexts/officialtexts.yml#/~1official-texts'
  '/official-texts/{officialTextId}':
    $ref: './paths/officialtexts/officialtexts.yml#/~1official-texts~1{officialTextId}'

  ### DOCUMENTS ###
  '/documents':
    $ref: './paths/documents/documents.yml#/~1documents'
  '/documents/{documentId}':
    $ref: './paths/documents/documents.yml#/~1documents~1{documentId}'

  ### PRIX SCIENTIFIQUES ###
  '/prices':
    $ref: './paths/prices/prices.yml#/~1prices'
  '/prices/{priceId}':
    $ref: './paths/prices/prices.yml#/~1prices~1{priceId}'

  ### PROJETS ###
  '/projects':
    $ref: './paths/projects/projects.yml#/~1projects'
  '/projects/{projectId}':
    $ref: './paths/projects/projects.yml#/~1projects~1{projectId}'
  '/projects/{projectId}/weblinks':
    $ref: './paths/projects/weblinks.yml#/~1projects~1{projectId}~1weblinks'
  '/projects/{projectId}/weblinks/{weblinkId}':
    $ref: './paths/projects/weblinks.yml#/~1projects~1{projectId}~1weblinks~1{weblinkId}'
  '/projects/{projectId}/localisations':
    $ref: './paths/projects/localisations.yml#/~1projects~1{projectId}~1localisations'
  '/projects/{projectId}/localisations/{localisationId}':
    $ref: './paths/projects/localisations.yml#/~1projects~1{projectId}~1localisations~1{localisationId}'

  ### TYPE DE DOCUMENTS ###
  '/document-types':
    $ref: './paths/document-types/document-types.yml#/~1document-types'
  '/document-types/{documentTypeId}':
    $ref: './paths/document-types/document-types.yml#/~1document-types~1{documentTypeId}'

  ### TYPE DE CONTACT GENERIC ###
  '/email-types':
    $ref: './paths/email-types/email-types.yml#/~1email-types'
  '/email-types/{emailTypeId}':
    $ref: './paths/email-types/email-types.yml#/~1email-types~1{emailTypeId}'
  
  ### PORTEFEUILLE MINISTERIELS ###
  '/ministerial-portfolios':
    $ref: './paths/ministerial-portfolios/ministerial-portfolios.yml#/~1ministerial-portfolios'
  '/ministerial-portfolios/{ministerialPortfolioId}':
    $ref: './paths/ministerial-portfolios/ministerial-portfolios.yml#/~1ministerial-portfolios~1{ministerialPortfolioId}'

components:
  parameters:
    filters:
      $ref: ./parameters/query/filters.yml
    skip:
      $ref: ./parameters/query/skip.yml
    limit:
      $ref: ./parameters/query/limit.yml
    sort:
      $ref: ./parameters/query/sort.yml
    documentId:
      $ref: ./parameters/ids/document-id.yml
    documentTypeId:
      $ref: ./parameters/ids/document-type-id.yml
    emailTypeId:
      $ref: ./parameters/ids/email-type-id.yml
    structureId:
      $ref: ./parameters/ids/structure-id.yml
    nameId:
      $ref: ./parameters/ids/name-id.yml
    emailId:
      $ref: ./parameters/ids/email-id.yml
    logoId:
      $ref: ./parameters/ids/logo-id.yml
    identifierId:
      $ref: ./parameters/ids/identifier-id.yml
    localisationId:
      $ref: ./parameters/ids/localisation-id.yml
    weblinkId:
      $ref: ./parameters/ids/weblink-id.yml
    socialmediaId:
      $ref: ./parameters/ids/social-media-id.yml
    termId:
      $ref: ./parameters/ids/term-id.yml
    categoryId:
      $ref: ./parameters/ids/category-id.yml
    relatedCategoryId:
      $ref: ./parameters/ids/related-category-id.yml
    relatedLegalCategoryId:
      $ref: ./parameters/ids/related-legal-category-id.yml
    legalCategoryId:
      $ref: ./parameters/ids/legal-category-id.yml
    priceId:
      $ref: ./parameters/ids/price-id.yml
    personId:
      $ref: ./parameters/ids/person-id.yml
    projectId:
      $ref: ./parameters/ids/project-id.yml
    officialTextId:
      $ref: ./parameters/ids/officialtext-id.yml
    newsId:
      $ref: ./parameters/ids/news-id.yml
    roleId:
      $ref: ./parameters/ids/role-id.yml
    relationshipId:
      $ref: ./parameters/ids/relationship-id.yml
    ministerialPortfolioId:
      $ref: ./parameters/ids/ministerial-portfolio-id.yml

  responses:
    BadRequest:
      $ref: './responses/errors/bad-request.yml'
    NotFound:
      $ref: './responses/errors/not-found.yml'
    Forbidden:
      $ref: './responses/errors/forbidden.yml'
    Unauthorized:
      $ref: './responses/errors/unauthorized.yml'
    ServerError:
      $ref: './responses/errors/server-error.yml'

  schemas:
    ### MODELS ###
    Category:
      $ref: './schemas/categories/category.yml'
    CategoryIdentifier:
      $ref: './schemas/categories/identifier.yml'
    CategoryLight:
      $ref: './schemas/categories/category-light.yml'
    CategoryWeblink:
      $ref: './schemas/categories/weblink.yml'
    CategoryRelationship:
      $ref: './schemas/commons/category-relationship.yml'
    Document:
      $ref: './schemas/documents/document.yml'
    DocumentLight:
      $ref: './schemas/documents/document-light.yml'
    DocumentType:
      $ref: './schemas/commons/nomenclature.yml'
    DocumentTypeLight:
      $ref: './schemas/commons/nomenclature-light.yml'
    EmailType:
      $ref: './schemas/commons/nomenclature.yml'
    EmailTypeLight:
      $ref: './schemas/commons/nomenclature-light.yml'
    LegalCategory:
      $ref: './schemas/legalcategories/legalcategory.yml'
    LegalCategoryLight:
      $ref: './schemas/legalcategories/legalcategory-light.yml'
    Localisation:
      $ref: './schemas/commons/localisation.yml'
    LocalisationLight:
      $ref: './schemas/commons/localisation-light.yml'
    Logo:
      $ref: './schemas/commons/logo.yml'
    MinisterialPortfolio:
      $ref: './schemas/commons/nomenclature.yml'
    MinisterialPortfolioLight:
      $ref: './schemas/commons/nomenclature-light.yml'
    OfficialText:
      $ref: './schemas/officialtexts/officialtext.yml'
    OfficialTextLight:
      $ref: './schemas/officialtexts/officialtext-light.yml'
    Person:
      $ref: './schemas/persons/person.yml'
    PersonIdentifier:
      $ref: './schemas/persons/identifier.yml'
    PersonLight:
      $ref: './schemas/persons/person-light.yml'
    PersonWeblink:
      $ref: './schemas/persons/weblink.yml'
    Price:
      $ref: './schemas/prices/price.yml'
    PriceLight:
      $ref: './schemas/prices/price-light.yml'
    Project:
      $ref: './schemas/projects/project.yml'
    ProjectLight:
      $ref: './schemas/projects/project-light.yml'
    ProjectWeblink:
      $ref: './schemas/projects/weblink.yml'
    Role:
      $ref: './schemas/roles/role.yml'
    RoleLight:
      $ref: './schemas/roles/role-light.yml'
    SocialMedia:
      $ref: './schemas/commons/social-media.yml'
    Structure:
      $ref: './schemas/structures/structure.yml'
    StructureCategory:
      $ref: './schemas/commons/category-relationship.yml'
    StructureEmail:
      $ref: './schemas/structures/email.yml'
    StructureIdentifier:
      $ref: './schemas/structures/identifier.yml'
    StructureLegalCategory:
      $ref: './schemas/structures/legalcategory.yml'
    StructureLight:
      $ref: './schemas/structures/structure-light.yml'
    StructureLocalisation:
      $ref: './schemas/commons/localisation.yml'
    StructureLocalisationLight:
      $ref: './schemas/commons/localisation-light.yml'
    StructureName:
      $ref: './schemas/structures/name.yml'
    StructureNameLight:
      $ref: './schemas/structures/name-light.yml'
    StructureWeblink:
      $ref: './schemas/structures/weblink.yml'
    Term:
      $ref: './schemas/terms/term.yml'
    TermLight:
      $ref: './schemas/terms/term-light.yml'
    TermWeblink:
      $ref: './schemas/terms/weblink.yml'


    ### PAYLOADS ###
    CategoryIdentifierPayload:
      $ref: './schemas/categories/identifier-payload.yml'
    CategoryPayload:
      $ref: './schemas/categories/category-payload.yml'
    CategoryWeblinkPayload:
      $ref: './schemas/categories/weblink-payload.yml'
    CategoryRelationshipPayload:
      $ref: './schemas/commons/category-relationship-payload.yml'
    DocumentPayload:
      $ref: './schemas/documents/document-payload.yml'
    DocumentTypePayload:
      $ref: './schemas/commons/nomenclature-payload.yml'
    EmailTypePayload:
      $ref: './schemas/commons/nomenclature-payload.yml'
    LegalCategoryPayload:
      $ref: './schemas/legalcategories/legalcategory-payload.yml'
    LogoPayload:
      $ref: './schemas/commons/logo-payload.yml'
    MinisterialPortfolioPayload:
      $ref: './schemas/commons/nomenclature-payload.yml'
    OfficialTextPayload:
      $ref: './schemas/officialtexts/officialtext-payload.yml'
    PersonIdentifierPayload:
      $ref: './schemas/persons/identifier-payload.yml'
    PersonPayload:
      $ref: './schemas/persons/person-payload.yml'
    PersonWeblinkPayload:
      $ref: './schemas/persons/weblink-payload.yml'
    PricePayload:
      $ref: './schemas/prices/price-payload.yml'
    ProjectPayload:
      $ref: './schemas/projects/project-payload.yml'
    ProjectWeblinkPayload:
      $ref: './schemas/projects/weblink-payload.yml'
    RolePayload:
      $ref: './schemas/roles/role-payload.yml'
    LocalisationPayload:
      $ref: './schemas/commons/localisation-payload.yml'
    SocialMediaPayload:
      $ref: './schemas/commons/social-media-payload.yml'
    StructureCreatePayload:
      $ref: './schemas/structures/structure-create-payload.yml'
    StructureEmailPayload:
      $ref: './schemas/structures/email-payload.yml'
    StructureIdentifierPayload:
      $ref: './schemas/structures/identifier-payload.yml'
    StructureLegalCategoryPayload:
      $ref: './schemas/structures/legalcategory-payload.yml'
    StructureLocalisationPayload:
      $ref: './schemas/commons/localisation-payload.yml'
    StructureNamePayload:
      $ref: './schemas/structures/name-payload.yml'
    StructureUpdatePayload:
      $ref: './schemas/structures/structure-update-payload.yml'
    StructureWeblinkPayload:
      $ref: './schemas/structures/weblink-payload.yml'
    TermPayload:
      $ref: './schemas/terms/term-payload.yml'
    TermWeblinkPayload:
      $ref: './schemas/terms/weblink-payload.yml'


    ### ENUMS ###
    CategoryIdentifierTypesEnum:
      $ref: './schemas/categories/enums/identifier-types.yml'
    CategoryWeblinkTypesEnum:
      $ref: './schemas/categories/enums/weblink-types.yml'
    OfficialTextNaturesEnum:
      $ref: './schemas/officialtexts/enums/nature.yml'
    OfficialTextTypesEnum:
      $ref: './schemas/officialtexts/enums/type.yml'
    PersonIdentifierTypesEnum:
      $ref: './schemas/persons/enums/identifier-types.yml'
    PersonWeblinkTypesEnum:
      $ref: './schemas/persons/enums/weblink-types.yml'
    ProjectWeblinkTypesEnum:
      $ref: './schemas/projects/enums/weblink-types.yml'
    SocialmediaTypesEnum:
      $ref: './schemas/commons/enums/social-media-types.yml'
    StructureIdentifierTypesEnum:
      $ref: './schemas/structures/enums/identifier-types.yml'
    StructureWeblinkTypesEnum:
      $ref: './schemas/structures/enums/weblink-types.yml'
    TermWeblinkTypesEnum:
      $ref: './schemas/terms/enums/weblink-types.yml'


    ### COMMON MODELS ###
    Error:
      $ref: './schemas/commons/error.yml'
    Metas:
      $ref: './schemas/commons/metas.yml'

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: Authentication with a Bearer token.