openapi: 3.0.1
info:
  title: Authentication.
  description: Authentication and UserManagment api.
  contact:
    email: frederic.olland@enseignementsup.gouv.fr
  license:
    name: MIT
    url: 'https://github.com/dataesr/paysage-api/LICENCE.md'
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/'
  - url: 'https://api.paysage.staging.dataesr.ovh/'
  - url: 'https://api.paysage.dataesr.ovh/'


paths:
  ### AUTH ###
  '/auth/signup':
    $ref: ./paths/auth/signup.yml
  '/auth/signin':
    $ref: ./paths/auth/signin.yml
  '/auth/signout':
    $ref: ./paths/auth/signout.yml
  '/auth/activate-account':
    $ref: ./paths/auth/activate-account.yml
  '/auth/refresh-access-token':
    $ref: ./paths/auth/refresh-access-token.yml
  '/auth/renew-activation-code':
    $ref: ./paths/auth/renew-activation-code.yml
  '/auth/send-password-renewal-code':
    $ref: ./paths/auth/send-password-renewal-code.yml
  '/auth/reset-password':
    $ref: ./paths/auth/reset-password.yml

  ### USERS ###
  '/users/{userId}':
    $ref: ./paths/users/users.yml#/User
  '/users':
    $ref: ./paths/users/users.yml#/Users

  ### CURRENT USER ###
  '/me':
    $ref: ./paths/users/me.yml#/Me
  '/me/password':
    $ref: ./paths/users/me.yml#/Password
  '/me/avatar':
    $ref: ./paths/users/me.yml#/Avatar

components:
  parameters:
    userId:
      $ref: ./parameters/ids/user-id.yml
    filters:
      $ref: ./parameters/query/filters.yml
    skip:
      $ref: ./parameters/query/skip.yml
    limit:
      $ref: ./parameters/query/limit.yml
    sort:
      $ref: ./parameters/query/sort.yml

  responses:
    BadRequest:
      $ref: './responses/errors/bad-request.yml'
    NotFound:
      $ref: './responses/errors/not-found.yml'
    Forbidden:
      $ref: './responses/errors/forbidden.yml'
    Unauthorized:
      $ref: './responses/errors/unauthorized.yml'
    ServerError:
      $ref: './responses/errors/server-error.yml'

  schemas:
    User:
      $ref: ./schemas/users/user.yml
    Me:
      $ref: ./schemas/users/me.yml
    SignInPayload:
      $ref: ./schemas/auth/signin-payload.yml
    SignUpPayload:
      $ref: ./schemas/auth/signup-payload.yml
    Tokens:
      $ref: ./schemas/auth/tokens.yml

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: Authentication with a Bearer token.