openapi: 3.0.1
info:
  title: Paysage-api.
  description: Documentation for the Paysage rest API routes.
  contact:
    email: frederic.olland@enseignementsup.gouv.fr
  license:
    name: MIT
    url: 'https://github.com/dataesr/paysage-api/LICENCE.md'
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/'


paths:
  ### CATEGORIES ##
  '/categories':
    $ref: './modules/categories/path/categories.yml'
  '/categories/{categoryId}':
    $ref: './modules/categories/path/category.yml'

  ### OFFICIAL DOCUMENTS ##
  '/official-documents':
    $ref: './modules/official-documents/path/official-documents.yml'
  '/official-documents/{officialDocumentId}':
    $ref: './modules/official-documents/path/official-document.yml'

  ### STRUCTURE ###
  '/structures':
    $ref: './modules/structures/path/structures.yml'
  '/structures/{structureId}':
    $ref: './modules/structures/path/structure.yml'
  '/structures/{structureId}/_status':
    $ref: './modules/structures/path/_status.yml'
  '/structures/{structureId}/identifiers':
    $ref: './modules/structures/path/identifiers.yml'
  '/structures/{structureId}/identifiers/{identifierId}':
    $ref: './modules/structures/path/identifier.yml'
  '/structures/{structureId}/names':
    $ref: './modules/structures/path/names.yml'
  '/structures/{structureId}/names/{nameId}':
    $ref: './modules/structures/path/name.yml'

components:
  parameters:
    $ref: './parameters/_index.yml'

  responses:
    $ref: './responses/_index.yml'

  schemas:
    Error:
      $ref: './schemas/error.yml'